<script>

// 3. Using Finally Block

try {

    console.log("executing try block");
    
}catch (error) {

    console.log("error caught");
    
}finally {
    console.log("Finally block executed");
    
}

</script>